name: Compilar XenonRecomp Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Descargar codigo fuente con submodulos
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Configurar CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DXENON_TESTS=OFF

    - name: Compilar solo el ejecutable principal
      run: cmake --build build --config Release --target XenonRecomp

    - name: Subir ejecutable xenon-recomp.exe
      uses: actions/upload-artifact@v4
      with:
        name: xenon-recomp-windows
        path: |
          build/**/xenon-recomp.exe
          build/Release/xenon-recomp.exe
          build/XenonRecomp/Release/xenon-recomp.exe
