name: Compilar XenonRecomp Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Descargar codigo fuente con submodulos
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Configurar CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release -DXENON_TESTS=OFF -DXENON_SAMPLES=OFF -DXXHASH_BUILD_XXHSUM=OFF

    - name: Compilar ignorando errores en utilidades secundarias
      run: cmake --build build --config Release -- /p:ContinueOnError=true /p:StopOnFirstFailure=false

    - name: Subir todo lo generado en build
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: xenon-recomp-windows
        path: build/
